{% set name = "uxf" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/uxf-{{ version }}.tar.gz
  sha256: b319f38d0faff6d332db12a851d18f53fa6b509b53f3706a9c5f86f5b0928fc7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - editabletuple
    - python >=3.8

test:
  imports:
    - uxf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mark-summerfield/uxf
  summary: Uniform eXchange Format, a plain text human readable optionally typed storage format.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
