{% set name = "uxf" %}
{% set version = "2.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/uxf-{{ version }}.tar.gz
  sha256: 8a0cf19064bf13a365d794710bffd336fef9c05492c8608f0b6b9fae0839c44d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - editabletuple
    - python >=3.8

test:
  imports:
    - uxf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mark-summerfield/uxf
  summary: Uniform eXchange Format, a plain text human readable optionally typed storage format.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
